# Generated by Django 2.2.15 on 2020-08-28 07:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2020, 8, 28, 7, 34, 24, 612814, tzinfo=utc))),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='video',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 28, 7, 34, 23, 840575, tzinfo=utc)),
        ),
    ]
