# Generated by Django 2.2.15 on 2020-08-28 07:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200828_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='video',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
