# Generated by Django 2.2.15 on 2020-08-28 07:44

from django.db import migrations, models

    
class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200828_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='videos',
            field=models.ManyToManyField(to='main.Video'),
        ),
        migrations.AddField(
            model_name='video',
            name='tags',
            field=models.ManyToManyField(to='main.Tag'),
        ),
    ]
