# Generated by Django 2.2.15 on 2020-09-08 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200828_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='date_created',
        ),
    ]
