# Generated by Django 2.2.15 on 2020-09-08 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_video_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='date_created',
        ),
    ]
