# Generated by Django 2.2.15 on 2020-09-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200909_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='search',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
