# Generated by Django 2.2.15 on 2020-09-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_video_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='tags',
            field=models.ManyToManyField(to='main.Tag'),
        ),
    ]
