# Generated by Django 2.2.15 on 2020-09-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_tag_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='search',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
