# Generated by Django 2.2.15 on 2020-09-16 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200916_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='search',
        ),
    ]
