# Generated by Django 2.2.15 on 2020-09-18 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20200917_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tagger',
            new_name='user',
        ),
    ]
