# Generated by Django 2.2.15 on 2020-09-23 12:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20200918_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
