# Generated by Django 2.2.15 on 2020-09-23 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_video_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='date_created',
        ),
    ]
