# Generated by Django 2.2.15 on 2020-10-08 20:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_video_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
